**Java的基本理念就是 “结构不佳的代码不能运行”**

## 基本异常
**异常情形**是指阻止当前方法或作用域继续执行的问题。把异常情形与普通问题相区分是非常重要的，所谓的普通问题是指，在当前环境下能够得到足够的信息，总能处理这个错误。而对于异常情形，就不能继续下去了，因为在**当前环境**下无法获得必要的信息来解决问题。你所能做的就是从当前环境跳出，并且把问题提交给上一级。

当抛出异常之后，有几件事会随之发生。首先，同Java中其他对象的创建一样，将使用**new**在堆上创建异常对象。然后，当前的执行路径被终止，并且从当前环境中弹出堆异常对象的引用。此时，异常处理机制接管程序，并开始寻找**异常处理程序**来寻找一个恰当的地方来继续执行程序，它的任务就是将程序从错误的状态中恢复，让程序换一种方式运行，要么继续运行。

```java
if(t = null) throw new NullPointerException();
```
上诉代码就是创建了一个空指针异常，并将这个异常从当前环境中"抛出"，这样就把错误信息传播到了"更大"的环境中。

为什么要这么看重异常呢？因为异常一旦发生，很有可能将不允许程序沿着正常的路径继续走下去。

## 捕获异常
在了解异常是如何捕获的之前，需要先了解**监控区域**这一概念。它是一段可能产生异常代码的代码，并且后面跟着处理这些异常的代码

#### try块
try块是一种特殊的块，可以用来捕获异常，我们可以在这个块中处理一些脆弱、容易发生错误的代码。
```java
try{
    // 处理一些脆弱、容易发生错误的代码
}
```
#### catch
抛出的异常必须在某个地方得到处理，这个“地点”就是异常处理程序，而且针对每个要捕获的异常，得准备相应的异常处理。异常处理程序紧跟在try块之后，以关键字**catch**来表示：
```java
try{
    // 处理一些脆弱、容易发生错误的代码
}catch(Type1 id1){
    //处理异常类型1
}catch(Type2 id2){
    //处理异常类型2
}
```
每个catch子句看起来就像是接收一个且仅接收一个特殊类型的参数的方法。

异常处理程序必须紧跟在**try**块之后。当异常抛出时，异常处理机制将负责搜寻参数与异常类型相匹配的第一个处理程序。然后进入**catch**子句执行，此时认为异常得到了处理，一旦**catch**语句结束，则处理程序的查找过程也就结束了。<font color="#1E88E5">不要误以为和*switch*语句一样</font>。

## 创建自定义异常
Java提供的异常体系不可能预见所有的错误，所以有时候可以自己定义异常类来表示程序中可能遇到的问题。要自己定义异常类，必须从已有的异常类中进行继承，最好是选择意思相近的异常来进行继承。

建立新的异常类最简单的方法就是让编译器为你产生默认的构造器。
```java
class  MyException extends Exception{}
class InheritingExceptions{
    public void f() throws MyException{
        System.out.println("从f()中抛出MyException");
    }
}

public class Test {
    public static void main(String[] args) {
        InheritingExceptions sed = new InheritingExceptions();
        try{
            sed.f();
        }catch (MyException e){
            System.out.println("捕获到了自定义错误");
        }
    }
}

```
## 异常说明
当我们编写一个可能会抛出异常的方法时，如何让别人也知道这个方法容易出错呢？
这时就需要我们使用**异常说明**，它属于方法声明的一部分，紧跟在形式参数列表之后。

异常说明使用了附加的关键字**throws**，后面接一个所有潜在异常类型的列表，它的表达形式如下：
```java
void f() throws TooBig,Toosmall,DivZero{
    //...
}
```
## 捕获所有异常
实际上，我们是可以只写一个异常处理程序来捕获所有类型的异常。通过异常类型的基类**Exception**就可以轻松做到这一点(事实上，还存在一些其他的基类，但Exception是同编程活动相关的基类)
```java
catch(Exception e){
    System.out.println("Caught an exception");
}
```
这将捕获所有异常，所以最好把它放在处理程序列表的末尾，以防它抢在其他处理程序之前先把异常捕获了。

因为**Exception**是与编程有关的所有异常类的基类，但它并不是最顶级的基类，它还有一个基类**Throwable**。并且从这个基类继承了其他方法。以下表格展示部分继承的方法。

| 方法名                       | 含义                                                         |
| ---------------------------- | ------------------------------------------------------------ |
| String getMessage()          | 获取详细信息                                                 |
| String getLocalizedMessage() | 获取本地详细信息                                             |
| String toString()            | 返回对**Throwable**的简单描述，要是有详细信息的话，也会把它包含在内 |
| void printStackTrace()       | 打印**Throwable**和**Throwable**的调用栈轨迹                 |


#### 调用栈
**printStackTrace**会打印调用栈的信息，它会显示“把你带到异常抛出地点”的方法调用序列。

**printStackTrace**方法所提供的信息可以通过**getStackTrace**方法来直接访问，这个方法将返回一个由栈轨迹中的元素所构成的数组，其中每一个元素都表示栈中的一帧。元素0是栈顶元素，并且是调用序列中的最后一个方法调用(这个**Throwable**被创建和抛出之处)。数组中的最后一个元素和栈底是调用序列中的第一个方法调用。

#### 重新抛出异常
有时候需要把刚捕获的异常重新抛出，尤其是在使用**Exception**捕获所有的异常的时候。既然已经得到了对当前异常对象的引用，可以直接把它重新抛出。
```java
catch(Exception e){
    System.out.println("向上继续抛出异常");
    throw e;
}
```
重新抛出异常会把异常抛给**上一级环境中的异常处理程序**，同一个**try**块的后续**catch**子句将被忽略。此外，异常对象的所有信息都得以保持，所以高一级环境中捕获此异常的处理程序可以从这个异常对象中的到所有信息。

我们也不需要为清理前一个异常对象而感到担心，或者说为异常对象的清理而担心。它们都是用**new**在堆上创建的对象，所以垃圾回收器会自动把它们清理掉。

## Java标准异常
**Throwable**这个类被用来表示任何可以作为异常被抛出的类。

**Throwable**对象有两种子类(从*Throwable*继承而得到的类型)：**Error**用来表示编译时和系统错误;**Exception**是可以抛出的基本类型。

#### RunTimeException

```java
public class NeverCaught{
    static void f(){
        throw new RunTimeException("From f()");
    }
    static void g(){
        f();
    }
    public static void main(String[] args){
        g();
    }
}
```
如果**RuntimeException**没有被捕获而直达main()，那么程序在退出前将调用异常的**printStackTrace()**方法。

只能在代码中忽略**RuntimeException**(及其子类)类型的异常，其他类型异常的处理都是由编译器强制实施的。究其原因，**RuntimeException**代表的是编程错误。
